# defined stages
stages:
  - build
  - test
  
cache:
  paths:
    - node_modules/

variables:
  PM2: '/home/nodejs/.nvm/versions/node/v8.8.0/bin/pm2'
   
    

# defined build
job1:
  stage: build
  tags:
    - bac-prod
  script:
    - whoami
    
# defined test
job2:
  stage: test
  script:
    - /usr/bin/git --version
    - /usr/bin/npm -v
    - /usr/bin/node -v
    - $PM2 l
    - /home/nodejs/.nvm/versions/node/v8.8.0/bin/pm2 l

    