# defined stages
stages:
  - build
  - test
  
cache:
  paths:
    - node_modules/
    
    

# defined build
job1:
  stage: build
  tags:
    - bac-prod
  script:
    - whoami
    
# defined test
job2:
  stage: test
  script:
    - /usr/bin/git --version
    - /usr/bin/npm -v
    - /usr/bin/node -v

    