# defined stages
stages:
  - build
  - test
  
cache:
  paths:
    - node_modules/
    
    
# defined job
job1:
  stage: test
  tags:
    - bac-testing
  script:
    - echo "I am job1"
    - echo "I am in test stage"
# defined job
job2:
  stage: build
  tags:
    - bac-prod
  script:
    - echo "I am job2"
    - pwd