# defined stages
stages:
  - install_deps
  - build
  - test
  
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    
# 安装依赖
install_deps:
  stage: install_deps
  only:
    - develop
    - master
  script:
    - npm install
    
# defined job
job1:
  stage: test
  tags:
    - bac-testing
  script:
    - echo "I am job1"
    - echo "I am in test stage"
# defined job
job2:
  stage: build
  tags:
    - bac-prod
  script:
    - echo "I am job2"
    - pwd