# 定義 stages
stages:
  - install_deps
  - test
  - deploy_test
  - deploy_production
 
  
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

variables:
  NODE: '/usr/bin/node'
  GIT: '/usr/bin/git'
  PM2: '/home/nodejs/.nvm/versions/node/v8.8.0/bin/pm2'
  NPM: '/usr/bin/npm'


# 安装依賴套件
install_deps:
  stage: install_deps
  before_script:
  - scl enable devtoolset-2 bash
  - source /opt/rh/devtoolset-2/enable
  - gcc --version
  only:
    - develop
    - master
  script:
    - $NPM -v
    - $NODE -v
    - npm -E install

# 程式測試
test:
  stage: test
  only:
    - develop
    - master
  script:
    - echo "Testing.."
    - $GIT --version
    - $PM2 l
    - echo "Test successed."
    

# 部署測試機
deploy_test:
  stage: deploy_test
  only:
    - develop
  tags:
    - bac-dev     
  script:
    - pm2 delete bacchus4web || true
    - pm2 start app.js --name bacchus4web
    
# 部署正式機
deploy_production:
  stage: deploy_production
  only:
    - master
  tags:
    - bac-prod     
  script:
    - $GIT branch    


    